apiVersion: v1
kind: ConfigMap
metadata:
  name: django-notes-config
  namespace: django-notes
data:
  ALLOWED_HOSTS: "*"
  DB_HOST: mysql-service
  DB_NAME: notesapp
  DB_PORT: "3306"
  DB_USER: notesuser
  DEBUG: "False"
  DJANGO_SETTINGS_MODULE: notesapp.settings
