apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: django-notes-ingress
  namespace: django-notes

  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/certificate-arn: <AWS_CERTIFICATE_ARN>

spec:
  ingressClassName: alb

  rules:
  - host: <YOUR_DOMAIN>

    http:
      paths:
      - path: /
        pathType: Prefix

        backend:
          service:
            name: django-notes-service
            port:
              number: 80
