apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: django-notes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306

        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root123

        - name: MYSQL_DATABASE
          value: notesapp

        - name: MYSQL_USER
          value: notesuser

        - name: MYSQL_PASSWORD
          value: notes123

        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql

      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
